/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src-ui/**/*.{ts,tsx}', './index.html'],
  theme: {
    extend: {
      colors: {
        base: 'var(--color-base)',
        mantle: 'var(--color-mantle)',
        crust: 'var(--color-crust)',
        text: 'var(--color-text)',
        subtext: {
          1: 'var(--color-subtext-1)',
          0: 'var(--color-subtext-0)',
        },
        overlay: {
          2: 'var(--color-overlay-2)',
          1: 'var(--color-overlay-1)',
          0: 'var(--color-overlay-0)',
        },
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        accent: 'var(--color-accent)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
        surface: {
          0: 'var(--color-surface-0)',
          1: 'var(--color-surface-1)',
          2: 'var(--color-surface-2)',
        },
        lavender: 'var(--color-lavender)',
        blue: 'var(--color-blue)',
        sapphire: 'var(--color-sapphire)',
        sky: 'var(--color-sky)',
        teal: 'var(--color-teal)',
        green: 'var(--color-green)',
        yellow: 'var(--color-yellow)',
        peach: 'var(--color-peach)',
        maroon: 'var(--color-maroon)',
        red: 'var(--color-red)',
        mauve: 'var(--color-mauve)',
        pink: 'var(--color-pink)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      transitionDuration: {
        fast: '150ms',
        base: '250ms',
        slow: '350ms',
      },
      screens: {
        sm: '640px',
        md: '900px',
        lg: '1280px',
        xl: '1536px',
      },
    },
  },
  plugins: [],
};
